package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ActivityLogger generated by hbm2java
 */
public class ActivityLogger  implements java.io.Serializable {


     private int id;
     private Login login;
     private Date dateTime;
     private String messageType;
     private String message;
     private String description;
     private String accessHost;

    public ActivityLogger() {
    }

	
    public ActivityLogger(int id, Login login) {
        this.id = id;
        this.login = login;
    }
    public ActivityLogger(int id, Login login, Date dateTime, String messageType, String message, String description, String accessHost) {
       this.id = id;
       this.login = login;
       this.dateTime = dateTime;
       this.messageType = messageType;
       this.message = message;
       this.description = description;
       this.accessHost = accessHost;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAccessHost() {
        return this.accessHost;
    }
    
    public void setAccessHost(String accessHost) {
        this.accessHost = accessHost;
    }




}


