package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Allowance generated by hbm2java
 */
public class Allowance  implements java.io.Serializable {


     private AllowanceId id;
     private AllowanceDonator allowanceDonator;
     private NeedyPerson needyPerson;
     private PrivateRecord privateRecord;
     private Date date;
     private String unit;
     private Double amount;
     private String comment;
     private String status;

    public Allowance() {
    }

	
    public Allowance(AllowanceId id, AllowanceDonator allowanceDonator, NeedyPerson needyPerson, PrivateRecord privateRecord) {
        this.id = id;
        this.allowanceDonator = allowanceDonator;
        this.needyPerson = needyPerson;
        this.privateRecord = privateRecord;
    }
    public Allowance(AllowanceId id, AllowanceDonator allowanceDonator, NeedyPerson needyPerson, PrivateRecord privateRecord, Date date, String unit,Double amount, String comment, String status) {
       this.id = id;
       this.allowanceDonator = allowanceDonator;
       this.needyPerson = needyPerson;
       this.privateRecord = privateRecord;
       this.date = date;
       this.unit = unit;
       this.amount = amount;
       this.comment = comment;
       this.status = status;
    }
   
    public AllowanceId getId() {
        return this.id;
    }
    
    public void setId(AllowanceId id) {
        this.id = id;
    }
    public AllowanceDonator getAllowanceDonator() {
        return this.allowanceDonator;
    }
    
    public void setAllowanceDonator(AllowanceDonator allowanceDonator) {
        this.allowanceDonator = allowanceDonator;
    }
    public NeedyPerson getNeedyPerson() {
        return this.needyPerson;
    }
    
    public void setNeedyPerson(NeedyPerson needyPerson) {
        this.needyPerson = needyPerson;
    }
    public PrivateRecord getPrivateRecord() {
        return this.privateRecord;
    }
    
    public void setPrivateRecord(PrivateRecord privateRecord) {
        this.privateRecord = privateRecord;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


