package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1



/**
 * DeathDetailId generated by hbm2java
 */
public class DeathDetailId  implements java.io.Serializable {


     private int id;
     private int needyPersonId;

    public DeathDetailId() {
    }

    public DeathDetailId(int id, int needyPersonId) {
       this.id = id;
       this.needyPersonId = needyPersonId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getNeedyPersonId() {
        return this.needyPersonId;
    }
    
    public void setNeedyPersonId(int needyPersonId) {
        this.needyPersonId = needyPersonId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeathDetailId) ) return false;
		 DeathDetailId castOther = ( DeathDetailId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getNeedyPersonId()==castOther.getNeedyPersonId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getNeedyPersonId();
         return result;
   }   


}


