package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DeathDetail generated by hbm2java
 */
public class DeathDetail  implements java.io.Serializable {


     private DeathDetailId id;
     private NeedyPerson needyPerson;
     private Date deathDate;
     private String reason;
     private String location;
     private String comment;

    public DeathDetail() {
    }

	
    public DeathDetail(DeathDetailId id, NeedyPerson needyPerson) {
        this.id = id;
        this.needyPerson = needyPerson;
    }
    public DeathDetail(DeathDetailId id, NeedyPerson needyPerson, Date deathDate, String reason, String location, String comment) {
       this.id = id;
       this.needyPerson = needyPerson;
       this.deathDate = deathDate;
       this.reason = reason;
       this.location = location;
       this.comment = comment;
    }
   
    public DeathDetailId getId() {
        return this.id;
    }
    
    public void setId(DeathDetailId id) {
        this.id = id;
    }
    public NeedyPerson getNeedyPerson() {
        return this.needyPerson;
    }
    
    public void setNeedyPerson(NeedyPerson needyPerson) {
        this.needyPerson = needyPerson;
    }
    public Date getDeathDate() {
        return this.deathDate;
    }
    
    public void setDeathDate(Date deathDate) {
        this.deathDate = deathDate;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


