package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1



/**
 * DistrictOfficer generated by hbm2java
 */
public class DistrictOfficer  implements java.io.Serializable {


     private int id;
     private District district;
     private Role role;
     private String type;

    public DistrictOfficer() {
    }

	
    public DistrictOfficer(int id, District district, Role role) {
        this.id = id;
        this.district = district;
        this.role = role;
    }
    public DistrictOfficer(int id, District district, Role role, String type) {
       this.id = id;
       this.district = district;
       this.role = role;
       this.type = type;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


