package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;

/**
 * DivisionalSecretariat generated by hbm2java
 */
public class DivisionalSecretariat  implements java.io.Serializable {


     private int id;
     @JsonBackReference
     private District district;
     private String name;
     @JsonBackReference
     private Set dsOfficiers = new HashSet(0);
     @JsonBackReference
     private Set needyPersons = new HashSet(0);

    public DivisionalSecretariat() {
    }

	
    public DivisionalSecretariat(int id, District district) {
        this.id = id;
        this.district = district;
    }
    public DivisionalSecretariat(int id, District district, String name, Set dsOfficiers, Set needyPersons) {
       this.id = id;
       this.district = district;
       this.name = name;
       this.dsOfficiers = dsOfficiers;
       this.needyPersons = needyPersons;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
   
    public Set getDsOfficiers() {
        return this.dsOfficiers;
    }
   
    public void setDsOfficiers(Set dsOfficiers) {
        this.dsOfficiers = dsOfficiers;
    }
    public Set getNeedyPersons() {
        return this.needyPersons;
    }
    
    public void setNeedyPersons(Set needyPersons) {
        this.needyPersons = needyPersons;
    }




}


