package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private int id;
     private NeedyPerson needyPerson;
     private String documentCategory;
     private String entityName;
     private Integer entityId;
     private String documentDescription;
     private String fileName;
     private String contentType;
     private byte[] content;
     private String remark;
     private Date insertDatetime;

    public Document() {
    }

	
    public Document(int id, NeedyPerson needyPerson) {
        this.id = id;
        this.needyPerson = needyPerson;
    }
    public Document(int id, NeedyPerson needyPerson, String documentCategory, String entityName, Integer entityId, String documentDescription, String fileName, String contentType, byte[] content, String remark, Date insertDatetime) {
       this.id = id;
       this.needyPerson = needyPerson;
       this.documentCategory = documentCategory;
       this.entityName = entityName;
       this.entityId = entityId;
       this.documentDescription = documentDescription;
       this.fileName = fileName;
       this.contentType = contentType;
       this.content = content;
       this.remark = remark;
       this.insertDatetime = insertDatetime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NeedyPerson getNeedyPerson() {
        return this.needyPerson;
    }
    
    public void setNeedyPerson(NeedyPerson needyPerson) {
        this.needyPerson = needyPerson;
    }
    public String getDocumentCategory() {
        return this.documentCategory;
    }
    
    public void setDocumentCategory(String documentCategory) {
        this.documentCategory = documentCategory;
    }
    public String getEntityName() {
        return this.entityName;
    }
    
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }
    public Integer getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }
    public String getDocumentDescription() {
        return this.documentDescription;
    }
    
    public void setDocumentDescription(String documentDescription) {
        this.documentDescription = documentDescription;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getContentType() {
        return this.contentType;
    }
    
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }




}


