package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1



/**
 * DsOfficier generated by hbm2java
 */
public class DsOfficier  implements java.io.Serializable {


     private int id;
     private DivisionalSecretariat divisionalSecretariat;
     private Role role;
     private String type;

    public DsOfficier() {
    }

	
    public DsOfficier(int id, DivisionalSecretariat divisionalSecretariat, Role role) {
        this.id = id;
        this.divisionalSecretariat = divisionalSecretariat;
        this.role = role;
    }
    public DsOfficier(int id, DivisionalSecretariat divisionalSecretariat, Role role, String type) {
       this.id = id;
       this.divisionalSecretariat = divisionalSecretariat;
       this.role = role;
       this.type = type;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DivisionalSecretariat getDivisionalSecretariat() {
        return this.divisionalSecretariat;
    }
    
    public void setDivisionalSecretariat(DivisionalSecretariat divisionalSecretariat) {
        this.divisionalSecretariat = divisionalSecretariat;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


