package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private int id;
     private PrivateRecord privateRecord;
     private Date beginDate;
     private Date endDate;
     private String venue;
     private String description;
     private String status;
     @JsonBackReference
     private Set needyPersonHasEvents = new HashSet(0);

    public Event() {
    }

	
    public Event(int id, PrivateRecord privateRecord) {
        this.id = id;
        this.privateRecord = privateRecord;
    }
    public Event(int id, PrivateRecord privateRecord, Date beginDate, Date endDate, String venue, String description, String status, Set needyPersonHasEvents) {
       this.id = id;
       this.privateRecord = privateRecord;
       this.beginDate = beginDate;
       this.endDate = endDate;
       this.venue = venue;
       this.description = description;
       this.status = status;
       this.needyPersonHasEvents = needyPersonHasEvents;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public PrivateRecord getPrivateRecord() {
        return this.privateRecord;
    }
    
    public void setPrivateRecord(PrivateRecord privateRecord) {
        this.privateRecord = privateRecord;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getVenue() {
        return this.venue;
    }
    
    public void setVenue(String venue) {
        this.venue = venue;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getNeedyPersonHasEvents() {
        return this.needyPersonHasEvents;
    }
    
    public void setNeedyPersonHasEvents(Set needyPersonHasEvents) {
        this.needyPersonHasEvents = needyPersonHasEvents;
    }




}


