package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int id;
     private SecurityQuestion securityQuestion;
     private User user;
     private String password;
     private String answer;
     private Integer noAttempts;
     private Set activityLoggers = new HashSet(0);

    public Login() {
    }

	
    public Login(int id, SecurityQuestion securityQuestion, User user) {
        this.id = id;
        this.securityQuestion = securityQuestion;
        this.user = user;
    }
    public Login(int id, SecurityQuestion securityQuestion, User user, String password, String answer, Integer noAttempts, Set activityLoggers) {
       this.id = id;
       this.securityQuestion = securityQuestion;
       this.user = user;
       this.password = password;
       this.answer = answer;
       this.noAttempts = noAttempts;
       this.activityLoggers = activityLoggers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SecurityQuestion getSecurityQuestion() {
        return this.securityQuestion;
    }
    
    public void setSecurityQuestion(SecurityQuestion securityQuestion) {
        this.securityQuestion = securityQuestion;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public Integer getNoAttempts() {
        return this.noAttempts;
    }
    
    public void setNoAttempts(Integer noAttempts) {
        this.noAttempts = noAttempts;
    }
    public Set getActivityLoggers() {
        return this.activityLoggers;
    }
    
    public void setActivityLoggers(Set activityLoggers) {
        this.activityLoggers = activityLoggers;
    }




}


