package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private int id;
     private User userByUserIdTo;
     private User userByUserIdFrom;
     private String description;
     private Date insertDatetime;

    public Message() {
    }

	
    public Message(int id, User userByUserIdTo, User userByUserIdFrom) {
        this.id = id;
        this.userByUserIdTo = userByUserIdTo;
        this.userByUserIdFrom = userByUserIdFrom;
    }
    public Message(int id, User userByUserIdTo, User userByUserIdFrom, String description, Date insertDatetime) {
       this.id = id;
       this.userByUserIdTo = userByUserIdTo;
       this.userByUserIdFrom = userByUserIdFrom;
       this.description = description;
       this.insertDatetime = insertDatetime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUserByUserIdTo() {
        return this.userByUserIdTo;
    }
    
    public void setUserByUserIdTo(User userByUserIdTo) {
        this.userByUserIdTo = userByUserIdTo;
    }
    public User getUserByUserIdFrom() {
        return this.userByUserIdFrom;
    }
    
    public void setUserByUserIdFrom(User userByUserIdFrom) {
        this.userByUserIdFrom = userByUserIdFrom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getInsertDatetime() {
        return this.insertDatetime;
    }
    
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }




}


