package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1



/**
 * NeedyPersonHasEvent generated by hbm2java
 */
public class NeedyPersonHasEvent  implements java.io.Serializable {


     private int id;
     private Event event;
     private NeedyPerson needyPerson;
     private String achievment;
     private String comment;
     private String status;

    public NeedyPersonHasEvent() {
    }

	
    public NeedyPersonHasEvent(int id, Event event, NeedyPerson needyPerson) {
        this.id = id;
        this.event = event;
        this.needyPerson = needyPerson;
    }
    public NeedyPersonHasEvent(int id, Event event, NeedyPerson needyPerson, String achievment, String comment, String status) {
       this.id = id;
       this.event = event;
       this.needyPerson = needyPerson;
       this.achievment = achievment;
       this.comment = comment;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public NeedyPerson getNeedyPerson() {
        return this.needyPerson;
    }
    
    public void setNeedyPerson(NeedyPerson needyPerson) {
        this.needyPerson = needyPerson;
    }
    public String getAchievment() {
        return this.achievment;
    }
    
    public void setAchievment(String achievment) {
        this.achievment = achievment;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


