package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NeedyPerson generated by hbm2java
 */
public class NeedyPerson  implements java.io.Serializable {


     private int id;
     private DivisionalSecretariat divisionalSecretariat;
     private Role role;
     private User user;
     private String code;
     private String firstName;
     private String lastName;
     private String fullName;
     private String nic;
     private Date dob;
     private String gender;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String postalCode;
     private String email;
     private String mobile;
     private String martialStatus;
     private String bloodGroup;

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
     private String educationalLevel;
     private Set needyPersonHasGuardians = new HashSet(0);
     private Set deathDetails = new HashSet(0);
     private Set needyLogins = new HashSet(0);
     private Set allowances = new HashSet(0);
     private Set documents = new HashSet(0);
     private Set privateRecordHasNeedyPersons = new HashSet(0);
     private Set needyPersonHasEvents = new HashSet(0);
     
     private int age;

    public NeedyPerson() {
    }

	
    public NeedyPerson(int id, DivisionalSecretariat divisionalSecretariat, Role role, User user) {
        this.id = id;
        this.divisionalSecretariat = divisionalSecretariat;
        this.role = role;
        this.user = user;
    }
    public NeedyPerson(int id, DivisionalSecretariat divisionalSecretariat, Role role, User user, String code, String firstName, String lastName, String fullName, String nic, Date dob, String gender, String addressLine1, String addressLine2, String city, String postalCode, String email, String mobile, String martialStatus, String bloodGroup, String educationalLevel, Set needyPersonHasGuardians, Set deathDetails, Set needyLogins, Set allowances, Set documents, Set privateRecordHasNeedyPersons, Set needyPersonHasEvents) {
       this.id = id;
       this.divisionalSecretariat = divisionalSecretariat;
       this.role = role;
       this.user = user;
       this.code = code;
       this.firstName = firstName;
       this.lastName = lastName;
       this.fullName = fullName;
       this.nic = nic;
       this.dob = dob;
       this.gender = gender;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.postalCode = postalCode;
       this.email = email;
       this.mobile = mobile;
       this.martialStatus = martialStatus;
       this.bloodGroup = bloodGroup;
       this.educationalLevel = educationalLevel;
       this.needyPersonHasGuardians = needyPersonHasGuardians;
       this.deathDetails = deathDetails;
       this.needyLogins = needyLogins;
       this.allowances = allowances;
       this.documents = documents;
       this.privateRecordHasNeedyPersons = privateRecordHasNeedyPersons;
       this.needyPersonHasEvents = needyPersonHasEvents;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DivisionalSecretariat getDivisionalSecretariat() {
        return this.divisionalSecretariat;
    }
    
    public void setDivisionalSecretariat(DivisionalSecretariat divisionalSecretariat) {
        this.divisionalSecretariat = divisionalSecretariat;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getMartialStatus() {
        return this.martialStatus;
    }
    
    public void setMartialStatus(String martialStatus) {
        this.martialStatus = martialStatus;
    }
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }
    public String getEducationalLevel() {
        return this.educationalLevel;
    }
    
    public void setEducationalLevel(String educationalLevel) {
        this.educationalLevel = educationalLevel;
    }
    public Set getNeedyPersonHasGuardians() {
        return this.needyPersonHasGuardians;
    }
    
    public void setNeedyPersonHasGuardians(Set needyPersonHasGuardians) {
        this.needyPersonHasGuardians = needyPersonHasGuardians;
    }
    public Set getDeathDetails() {
        return this.deathDetails;
    }
    
    public void setDeathDetails(Set deathDetails) {
        this.deathDetails = deathDetails;
    }
    public Set getNeedyLogins() {
        return this.needyLogins;
    }
    
    public void setNeedyLogins(Set needyLogins) {
        this.needyLogins = needyLogins;
    }
    public Set getAllowances() {
        return this.allowances;
    }
    
    public void setAllowances(Set allowances) {
        this.allowances = allowances;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }
    public Set getPrivateRecordHasNeedyPersons() {
        return this.privateRecordHasNeedyPersons;
    }
    
    public void setPrivateRecordHasNeedyPersons(Set privateRecordHasNeedyPersons) {
        this.privateRecordHasNeedyPersons = privateRecordHasNeedyPersons;
    }
    public Set getNeedyPersonHasEvents() {
        return this.needyPersonHasEvents;
    }
    
    public void setNeedyPersonHasEvents(Set needyPersonHasEvents) {
        this.needyPersonHasEvents = needyPersonHasEvents;
    }




}


