package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1



/**
 * NeedyPersonHasGuardian generated by hbm2java
 */
public class NeedyPersonHasGuardian  implements java.io.Serializable {


     private int id;
     private Guardian guardian;
     private NeedyPerson needyPerson;
     private Integer startingYear;
     private Integer endingYear;

    public NeedyPersonHasGuardian() {
    }

	
    public NeedyPersonHasGuardian(int id, Guardian guardian, NeedyPerson needyPerson) {
        this.id = id;
        this.guardian = guardian;
        this.needyPerson = needyPerson;
    }
    public NeedyPersonHasGuardian(int id, Guardian guardian, NeedyPerson needyPerson, Integer startingYear, Integer endingYear) {
       this.id = id;
       this.guardian = guardian;
       this.needyPerson = needyPerson;
       this.startingYear = startingYear;
       this.endingYear = endingYear;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Guardian getGuardian() {
        return this.guardian;
    }
    
    public void setGuardian(Guardian guardian) {
        this.guardian = guardian;
    }
    public NeedyPerson getNeedyPerson() {
        return this.needyPerson;
    }
    
    public void setNeedyPerson(NeedyPerson needyPerson) {
        this.needyPerson = needyPerson;
    }
    public Integer getStartingYear() {
        return this.startingYear;
    }
    
    public void setStartingYear(Integer startingYear) {
        this.startingYear = startingYear;
    }
    public Integer getEndingYear() {
        return this.endingYear;
    }
    
    public void setEndingYear(Integer endingYear) {
        this.endingYear = endingYear;
    }




}


