package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NeedyActivityLogger generated by hbm2java
 */
public class NeedyActivityLogger  implements java.io.Serializable {


     private int id;
     private NeedyLogin needyLogin;
     private Date dateTime;
     private String messageType;
     private String message;
     private String description;
     private String accessHost;

    public NeedyActivityLogger() {
    }

	
    public NeedyActivityLogger(int id, NeedyLogin needyLogin) {
        this.id = id;
        this.needyLogin = needyLogin;
    }
    public NeedyActivityLogger(int id, NeedyLogin needyLogin, Date dateTime, String messageType, String message, String description, String accessHost) {
       this.id = id;
       this.needyLogin = needyLogin;
       this.dateTime = dateTime;
       this.messageType = messageType;
       this.message = message;
       this.description = description;
       this.accessHost = accessHost;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NeedyLogin getNeedyLogin() {
        return this.needyLogin;
    }
    
    public void setNeedyLogin(NeedyLogin needyLogin) {
        this.needyLogin = needyLogin;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getAccessHost() {
        return this.accessHost;
    }
    
    public void setAccessHost(String accessHost) {
        this.accessHost = accessHost;
    }




}


