package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;

/**
 * PrivateRecord generated by hbm2java
 */
public class PrivateRecord  implements java.io.Serializable {


     private int id;
     private String type;
     private String name;
     private String subName;
     @JsonBackReference
     private Set events = new HashSet(0);
     @JsonBackReference
     private Set privateRecordHasNeedyPersons = new HashSet(0);
     @JsonBackReference
     private Set allowances = new HashSet(0);
     @JsonBackReference
     private Set allowanceDonators = new HashSet(0);

    public PrivateRecord() {
    }

	
    public PrivateRecord(int id) {
        this.id = id;
    }
    public PrivateRecord(int id, String type, String name, String subName, Set events, Set privateRecordHasNeedyPersons, Set allowances, Set allowanceDonators) {
       this.id = id;
       this.type = type;
       this.name = name;
       this.subName = subName;
       this.events = events;
       this.privateRecordHasNeedyPersons = privateRecordHasNeedyPersons;
       this.allowances = allowances;
       this.allowanceDonators = allowanceDonators;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSubName() {
        return this.subName;
    }
    
    public void setSubName(String subName) {
        this.subName = subName;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
    public Set getPrivateRecordHasNeedyPersons() {
        return this.privateRecordHasNeedyPersons;
    }
    
    public void setPrivateRecordHasNeedyPersons(Set privateRecordHasNeedyPersons) {
        this.privateRecordHasNeedyPersons = privateRecordHasNeedyPersons;
    }
    public Set getAllowances() {
        return this.allowances;
    }
    
    public void setAllowances(Set allowances) {
        this.allowances = allowances;
    }
    public Set getAllowanceDonators() {
        return this.allowanceDonators;
    }
    
    public void setAllowanceDonators(Set allowanceDonators) {
        this.allowanceDonators = allowanceDonators;
    }




}


