package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
public class Province  implements java.io.Serializable {


     private int id;
     private String name;
     @JsonBackReference
     private Set provinceOfficers = new HashSet(0);
     @JsonBackReference
     private Set districts = new HashSet(0);

    public Province() {
    }

	
    public Province(int id) {
        this.id = id;
    }
    public Province(int id, String name, Set provinceOfficers, Set districts) {
       this.id = id;
       this.name = name;
       this.provinceOfficers = provinceOfficers;
       this.districts = districts;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProvinceOfficers() {
        return this.provinceOfficers;
    }
    
    public void setProvinceOfficers(Set provinceOfficers) {
        this.provinceOfficers = provinceOfficers;
    }
    public Set getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Set districts) {
        this.districts = districts;
    }




}


