package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private int id;
     private String name;
     private Set provinceOfficers = new HashSet(0);
     private Set needyPersons = new HashSet(0);
     private Set users = new HashSet(0);
     private Set dsOfficiers = new HashSet(0);
     private Set districtOfficers = new HashSet(0);
     private Set roleHasPermissions = new HashSet(0);

    public Role() {
    }

	
    public Role(int id) {
        this.id = id;
    }
    public Role(int id, String name, Set provinceOfficers, Set needyPersons, Set users, Set dsOfficiers, Set districtOfficers, Set roleHasPermissions) {
       this.id = id;
       this.name = name;
       this.provinceOfficers = provinceOfficers;
       this.needyPersons = needyPersons;
       this.users = users;
       this.dsOfficiers = dsOfficiers;
       this.districtOfficers = districtOfficers;
       this.roleHasPermissions = roleHasPermissions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProvinceOfficers() {
        return this.provinceOfficers;
    }
    
    public void setProvinceOfficers(Set provinceOfficers) {
        this.provinceOfficers = provinceOfficers;
    }
    public Set getNeedyPersons() {
        return this.needyPersons;
    }
    
    public void setNeedyPersons(Set needyPersons) {
        this.needyPersons = needyPersons;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getDsOfficiers() {
        return this.dsOfficiers;
    }
    
    public void setDsOfficiers(Set dsOfficiers) {
        this.dsOfficiers = dsOfficiers;
    }
    public Set getDistrictOfficers() {
        return this.districtOfficers;
    }
    
    public void setDistrictOfficers(Set districtOfficers) {
        this.districtOfficers = districtOfficers;
    }
    public Set getRoleHasPermissions() {
        return this.roleHasPermissions;
    }
    
    public void setRoleHasPermissions(Set roleHasPermissions) {
        this.roleHasPermissions = roleHasPermissions;
    }




}


