package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1



/**
 * RoleHasPermission generated by hbm2java
 */
public class RoleHasPermission  implements java.io.Serializable {


     private int id;
     private Permission permission;
     private Role role;

    public RoleHasPermission() {
    }

    public RoleHasPermission(int id, Permission permission, Role role) {
       this.id = id;
       this.permission = permission;
       this.role = role;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Permission getPermission() {
        return this.permission;
    }
    
    public void setPermission(Permission permission) {
        this.permission = permission;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


