package com.pojos;
// Generated Sep 15, 2018 12:52:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private Role role;
     private String firstName;
     private String lastName;
     private String nic;
     private String dob;
     private String gender;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String postalCode;
     private String email;
     private String mobile;
     private Date regDate;
     private Set logins = new HashSet(0);
     private Set needyPersons = new HashSet(0);
     private Set messagesForUserIdTo = new HashSet(0);
     private Set messagesForUserIdFrom = new HashSet(0);

    public User() {
    }

	
    public User(int id, Role role) {
        this.id = id;
        this.role = role;
    }
    public User(int id, Role role, String firstName, String lastName, String nic, String dob, String gender, String addressLine1, String addressLine2, String city, String postalCode, String email, String mobile, Date regDate, Set logins, Set needyPersons, Set messagesForUserIdTo, Set messagesForUserIdFrom) {
       this.id = id;
       this.role = role;
       this.firstName = firstName;
       this.lastName = lastName;
       this.nic = nic;
       this.dob = dob;
       this.gender = gender;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.postalCode = postalCode;
       this.email = email;
       this.mobile = mobile;
       this.regDate = regDate;
       this.logins = logins;
       this.needyPersons = needyPersons;
       this.messagesForUserIdTo = messagesForUserIdTo;
       this.messagesForUserIdFrom = messagesForUserIdFrom;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getNeedyPersons() {
        return this.needyPersons;
    }
    
    public void setNeedyPersons(Set needyPersons) {
        this.needyPersons = needyPersons;
    }
    public Set getMessagesForUserIdTo() {
        return this.messagesForUserIdTo;
    }
    
    public void setMessagesForUserIdTo(Set messagesForUserIdTo) {
        this.messagesForUserIdTo = messagesForUserIdTo;
    }
    public Set getMessagesForUserIdFrom() {
        return this.messagesForUserIdFrom;
    }
    
    public void setMessagesForUserIdFrom(Set messagesForUserIdFrom) {
        this.messagesForUserIdFrom = messagesForUserIdFrom;
    }




}


